### PR TITLE
Check what's going wrong on macOS CI in some cases

### PR DESCRIPTION
**Pull request by finagolfin**

### CODE REVIEW

**Comment by finagolfin** [comment]
I think something has gone wrong when cross-compiling using the mac OSS trunk toolchain for Android, will test this more later.

**Comment by finagolfin** [comment]
I got `swift-argument-parser` building on the mac CI, but the trunk OSS toolchain for macOS appears broken when cross-compiling.

@marcprux, if you have the latest Sep. 25 trunk snapshot of the linux static SDK available, try cross-compiling a package with it from macOS and see if it works. If you don't get to it, I'll script it on the CI later and check.

The CI will start uploading multi-arch SDKs in a couple hours because your pulls were merged today. Try using that new SDK, particularly testing an Android app with the new unversioned Termux libraries, and let me know of any problems.

**Comment by marcprux** [comment]
> @marcprux, if you have the latest Sep. 25 trunk snapshot of the linux static SDK available, try cross-compiling a package with it from macOS and see if it works. If you don't get to it, I'll script it on the CI later and check.

I would, but the Static SDK link from https://www.swift.org/install/macos/ (pointing to https://download.swift.org/development/static-sdk/swift-DEVELOPMENT-SNAPSHOT-2024-09-25/swift-DEVELOPMENT-SNAPSHOT-2024-09-25-a_static-linux-0.0.1.artifactbundle.tar.gz) is 404. And all the static SDK links from https://www.swift.org/download/ are broken (as I reported at https://github.com/swiftlang/swift-org-website/issues/823).

Do you know anywhere else I might find it?

**Comment by marcprux** [comment]
> Try using that new SDK, particularly testing an Android app with the new unversioned Termux libraries, and let me know of any problems.

It would have worked, except for https://github.com/finagolfin/swift-android-sdk/pull/178. If I manually add in the new `cares.so` library, then everything links fine when launched from an apk.

**Comment by finagolfin** [comment]
> Do you know anywhere else I might find it?

Nope, I had forgotten about that issue you filed. I'll see about generating a trunk linux SDK on the mac CI and checking it that way.

**Pull request merged**
